### PR TITLE
ci: Add CodeQL analysis

### PR DESCRIPTION
**Pull request by twpayne**
This adds CodeQL analysis to Hubble, similar to https://github.com/cilium/cilium/pull/14514.

### CODE REVIEW

**Comment by kaworu** [comment]
Thanks @twpayne for the PR! Is the "analysis not found" expected? https://github.com/cilium/hubble/pull/475/checks?check_run_id=1807367595

**Comment by twpayne** [comment]
Nope, definitely not expected. With these CI changes, you only get to debug them once you push a branch :)

**Comment by kaworu** [comment]
So what would be the way to make forward progress on this?

**Comment by twpayne** [comment]
> So what would be the way to make forward progress on this?

I need to do some debugging :)

**Comment by twpayne** [comment]
I think this is just because this is the first CodeQL analysis for this repo, so there's no other analysis to compare with to find what's been fixed or newly introduced. [Relevant doc](https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository#reasons-for-the-missing-analysis-message).

**Comment by kaworu** [comment]
> I think this is just because this is the first CodeQL analysis for this repo, so there's no other analysis to compare with to find what's been fixed or newly introduced. Relevant doc.

That make sense. How about this: we merge this PR and you make another (dummy or cosmetic) PR to see if everything work as expected?

**Review by kaworu — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Comment by twpayne** [comment]
> That make sense. What we could do is merge this PR, and then you make another (dummy or cosmetic) PR to see if everything work as expected. How does that sound?

Good idea. I've rebased #474 on top of this, which should serve the purpose.

**Pull request merged**
