### PR TITLE
cmd/peer: Refactor and test processing of response

### PR DESCRIPTION
**Pull request by simar7**
This PR refactors a small piece of processing code and adds tests.

Signed-off-by: Simarpreet Singh <simar@linux.com>

### CODE REVIEW

**Comment by simar7** [comment]
Some insight: Initially I wanted to treat the `runWatch` function as a black box and write a test for it to simulate state changes. While it was exciting at first, the test setup for this proved to be quite involved since `runWatch` runs a busy loop and is only controllable through the error return value from `b.Recv()`. 

In favour of simplicity and readability, I instead took this approach. This refactors and tests the functional aspects of processing an event, rather than its setup.

**Comment by rolinh** [comment]
> Initially I wanted to treat the runWatch function as a black box and write a test for it to simulate state changes. While it was exciting at first, the test setup for this proved to be quite involved since runWatch runs a busy loop and is only controllable through the error return value from b.Recv().

While not trivial, it's probably simpler than you think. We actually have[ a fake peer client in the Cilium tree](https://github.com/cilium/cilium/blob/198fe64d79b53c983ba74f09f5c7a1c34408666d/pkg/hubble/testutils/fake.go#L132-L159). It is actually used for [Hubble Relay's pool manager unit tests](https://github.com/cilium/cilium/blob/master/pkg/hubble/relay/pool/manager_test.go).
As part of the test, you can simply instantiate a fake peer client add pass it to `runWatch()`. You don't have to go this route though but it should actually be fairly simple to implement as all that needs to be done is return something when the fake peer client's `Notify` method is called.

**Comment by simar7** [comment]
> > Initially I wanted to treat the runWatch function as a black box and write a test for it to simulate state changes. While it was exciting at first, the test setup for this proved to be quite involved since runWatch runs a busy loop and is only controllable through the error return value from b.Recv().
> 
> While not trivial, it's probably simpler than you think. We actually have[ a fake peer client in the Cilium tree](https://github.com/cilium/cilium/blob/198fe64d79b53c983ba74f09f5c7a1c34408666d/pkg/hubble/testutils/fake.go#L132-L159). It is actually used for [Hubble Relay's pool manager unit tests](https://github.com/cilium/cilium/blob/master/pkg/hubble/relay/pool/manager_test.go).
> As part of the test, you can simply instantiate a fake peer client add pass it to `runWatch()`. You don't have to go this route though :) But it should actually be fairly simple to implement as all that needs to be done is to return something when the fake peer client's `Notify` method is called.

Thanks for that insight @rolinh – I unknowingly did venture into that route on my own before charting on the current way but I will re-visit it once again. The pool manager unit tests look very interesting in their approach. Definitely something to learn from.

**Comment by simar7** [comment]
So I tried to use the testutils package as is it has the test doubles needed in this case but I ran into a small hiccup. I believe the package isn't importable outside the repository as it doesn't have a `go.mod` within the package. https://github.com/cilium/cilium/tree/master/pkg/hubble/testutils

I tried to validate the above by doing the following, which seems to work:

1. Locally cloning a copy of cilium repo
2. Adding the appropriate `go.mod` 
```
$ testutils git:(master) ✗ cat go.mod 
module github.com/pkg/hubble/testutils

go 1.16
```
3. Doing a `replace` directive to point at the locally cloned cilium repo. 
```
replace (
	github.com/cilium/cilium/pkg/hubble/testutils => /Users/simar/repos/cilium/pkg/hubble/testutils
)
```

I believe testutils may or may not have been intended to use outside of the cilium repo and as a result it isn't importable as a go module. It should be a simple addition to make `testutils` importable and I can contribute a PR for it if that's OK.

In the interest of slicing thin, do you think we should keep adding tests for `runWatch()` in a separate PR and merge this if it looks good to you as is?

**Comment by rolinh** [comment]
> I believe the package isn't importable outside the repository as it doesn't have a go.mod within the package.

Actually, this is not the issue at play here. We suffer from a problem with the grpc dependency which broke version compatibility and this affects a cilium dependency (etcd). We managed to use a recent grpc version in this repository because so far, nothing we pulled from cilium pulled the etcd dependency. It seems that pulling in the `testutils` package does :/ :
```
$ go mod tidy && go mod vendor && go mod verify
go: finding module for package google.golang.org/grpc/naming
github.com/cilium/hubble/cmd/peer tested by
        github.com/cilium/hubble/cmd/peer.test imports
        github.com/cilium/cilium/pkg/hubble/testutils imports
        github.com/cilium/cilium/pkg/ipcache imports
        github.com/cilium/cilium/pkg/kvstore imports
        go.etcd.io/etcd/clientv3 tested by
        go.etcd.io/etcd/clientv3.test imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/proxy/grpcproxy imports
        google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.36.0), but does not contain package google.golang.org/grpc/naming
``` 
More information about this problem [here](https://github.com/cilium/cilium/pull/13405#issuecomment-704766707). We're currently pending on a new release of the etcd dependency which should fix this problem.

> In the interest of slicing thin, do you think we should keep adding tests for runWatch() in a separate PR and merge this if it looks good to you as is?

As I can't tell when the above issue will be resolved, I think your proposal is reasonable.

**Review by rolinh — APPROVED** [review]

**Comment by simar7** [comment]
> > I believe the package isn't importable outside the repository as it doesn't have a go.mod within the package.
> 
> Actually, this is not the issue at play here. We suffer from a problem with the grpc dependency which broke version compatibility and this affects a cilium dependency (etcd). We managed to use a recent grpc version in this repository because so far, nothing we pulled from cilium pulled the etcd dependency. It seems that pulling in the `testutils` package does :/ :
> 
> ```
> $ go mod tidy && go mod vendor && go mod verify
> go: finding module for package google.golang.org/grpc/naming
> github.com/cilium/hubble/cmd/peer tested by
>         github.com/cilium/hubble/cmd/peer.test imports
>         github.com/cilium/cilium/pkg/hubble/testutils imports
>         github.com/cilium/cilium/pkg/ipcache imports
>         github.com/cilium/cilium/pkg/kvstore imports
>         go.etcd.io/etcd/clientv3 tested by
>         go.etcd.io/etcd/clientv3.test imports
>         go.etcd.io/etcd/integration imports
>         go.etcd.io/etcd/proxy/grpcproxy imports
>         google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.36.0), but does not contain package google.golang.org/grpc/naming
> ```
> 
> More information about this problem [here](https://github.com/cilium/cilium/pull/13405#issuecomment-704766707). We're currently pending on a new release of the etcd dependency which should fix this problem.
> 
> > In the interest of slicing thin, do you think we should keep adding tests for runWatch() in a separate PR and merge this if it looks good to you as is?
> 
> As I can't tell when the above issue will be resolved, I think your proposal is reasonable.

Oh I see. I'll subscribe to that PR in that case to keep track.

**Pull request merged**
