### PR TITLE
k8s: add high-level kube apiserver client

### PR DESCRIPTION
**Pull request by Rolinh**
The goal is to be able to retrieve the list of hubble peers using the kubernetes API. This will be useful to implement the multi-node feature. 

ref #89

### CODE REVIEW

**Comment by michi-covalent** [comment]
so i guess we need to talk to k8s api after all?

**Comment by Rolinh** [comment]
@michi-covalent Yup, for non-embedded mode. I'll define an interface though so one can implement it using the k8s client for non-embedded mode and using cilium node manager when embedded.
There are other PRs in the work ;)

**Comment by michi-covalent** [comment]
guess this is not related
```
--- FAIL: TestRingReader_NextFollow (0.00s)
    --- FAIL: TestRingReader_NextFollow/read_2,_start_at_position_0,_expect_timeout=false (0.00s)
        ring_reader_test.go:219: 
            	Error Trace:	ring_reader_test.go:219
            	Error:      	Not equal: 
            	            	expected: []*v1.Event{(*v1.Event)(0xc000521180), (*v1.Event)(0xc0005211a0)}
            	            	actual  : []*v1.Event{(*v1.Event)(0xc000520f20), (*v1.Event)(nil)}
            	            	
            	            	Diff:
            	            	--- Expected
```

**Comment by Rolinh** [comment]
> lgtm, although i feel like we should go all in with the embedded mode and deprecate the standalone mode altogether.

What about support for Cilium < 1.8?

**Comment by Rolinh** [comment]
Hubble embedded will be a requirement for the upcoming multi-node feature in order to reduce code complexity and to avoid overloading the kube apiserver. Thus, let's close this PR.

**Comment by Rolinh** [comment]
Re-opening. All things considered, this will be useful when running a hubble client that is not necessarily embedded into cilium in order to discover hubble peers.

**Comment by Rolinh** [comment]
Will close for now, this might be implemented differently.

**Pull request closed without merging**
