### PR TITLE
vendor: update cilium to v1.7.0

### PR DESCRIPTION
**Pull request by Rolinh**
Now that cilium v1.7.0 final release is out, track the final release rather than the RCs.

/cc @michi-covalent 
ref #127, #97

### CODE REVIEW

**Comment by michi-covalent** [comment]
go mod is failing on cilium side with this error:
```
% go mod vendor
go: finding github.com/cilium/hubble 75e5cd56faa8f6e2b12d07d56318962346ba562d
go: github.com/cilium/hubble@v0.0.0-20200224170852-75e5cd56faa8 requires
        github.com/cilium/cilium@v1.7.0 requires
        k8s.io/apiextensions-apiserver@v0.0.0: reading k8s.io/apiextensions-apiserver/go.mod at revision v0.0.0: unknown revision v0.0.0
```

i guess the latest cilium has conflicting dependencies with v1.7.0: https://github.com/cilium/cilium/commit/f31485a15698e7e6fb74224ea17fc823540594dc

**Comment by Rolinh** [comment]
@michi-covalent Maybe we just have to track cilium-master instead?
Then we would also benefit from https://github.com/cilium/cilium/pull/10221 which removed almost all replace directives in the `go.mod` file that we had to replicate in hubble's `go.mod`.

**Comment by michi-covalent** [comment]
let's do that for now. on a related note, there is a discussion going on here about the circular dependency between cilium and hubble: https://github.com/cilium/cilium/pull/10238#pullrequestreview-363273544

**Comment by Rolinh** [comment]
> let's do that for now. 

See #136

**Pull request merged**
