### PR TITLE
Fix link to the grafana.json file

### LINKED ISSUE #1: Page note found on deploy-hubble-and-grafana/grafana.json
A `.` is missing from the link in metrics.md to the grafana.json definition file.

### PR DESCRIPTION
**Pull request by Skarlso**
Closes #1

### CODE REVIEW

**Comment by gandro** [comment]
Thanks for your contribution! Could you please sign-off your commit as per the [Cilium Contributor Guide](https://docs.cilium.io/en/stable/contributing/contributing/#developer-s-certificate-of-origin)?

**Comment by Skarlso** [comment]
@gandro Hi. Err... It's not really clear to me where I should add that line? In the commit message?

**Comment by gandro** [comment]
> @gandro Hi. Err... It's not really clear to me where I should add that line? In the commit message?

Yes. The preferred way is to use `git commit --signoff` - git will add to your commit message automatically.

**Comment by Skarlso** [comment]
@tgraf @gandro thank you! :)

**Comment by glibsm** [comment]
Thank you and congrats on PR #1 ! 🎉

**Comment by Skarlso** [comment]
Thank you! :) :)

**Pull request merged**
