### PR TITLE
vendor: bump github.com/cilium/cilium to latest master

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by rolinh** [comment]
I'd suggest that we keep tracking cilium's `master` branch in hubble `master` (as we'll inevitably do this to support upcoming API additions) and track v1.10 in the v0.8 branch.

**Comment by tklauser** [comment]
> I'd suggest that we keep tracking cilium's `master` branch in hubble `master` (as we'll inevitably do this to support upcoming API additions) and track v1.10 in the v0.8 branch.

That's a good point. I'll repurpose this PR to update to latest cilium `master` (not sure whether it's worth it at this point, though?) and send a separate PR against `v0.8` updating to cilium `v1.10.0`.

**Comment by rolinh** [comment]
> I'll repurpose this PR to update to latest cilium `master` (not sure whether it's worth it at this point, though?) and send a separate PR against `v0.8` updating to cilium `v1.10.0`.

Probably other than it will make it clear that the master branch is tracking cilium master branch.

**Review by rolinh — CHANGES_REQUESTED** [review]
I think that the `go.universe.tf/metallb` replace directive does not match the version in cilium master.

**Comment by tklauser** [comment]
> I think that the `go.universe.tf/metallb` replace directive does not match the version in cilium master.

🤦 thanks for pointing this out

**Review by rolinh — APPROVED** [review]

**Pull request merged**
